### ISSUE TITLE
Using by ssh console 

### ISSUE THREAD

**Issue by dzaczek** [juliojsb/sarviewer#2] opened 2018-01-08 07:26 UTC
Hi 
I have a lite bug when i try use system system_data_reader 
"RuntimeError: could not open display  "

Matplotlib:
https://asciinema.org/a/98RyJWwpmLx5xisX3yrFCLzt4
Gnuplot:
https://asciinema.org/a/v2EvdPfXTRCxxtOXyjyXXCSgr

**Comment by dzaczek** [comment] 2018-01-08 08:07
Is problem with time variable current format is HH:MM and sar required HH:MM:SS

`# Default start time to parse statistics
start_time="00:00:00"

# Default end time to parse statistics
end_time="23:59:59"
~                         `
  
This is resolving only problem generating data by gnuplot,  matplotlib still exist

**Comment by juliojsb** [comment] 2018-01-08 19:41
Hi @dzaczek ,

I think there are two separate issues here: time format and matplotlib rendering.

Format of start_time and end_time was causing problems when parsing the logs with **sysstat version 10.1.5**. In Debian Stretch with sysstat 11.4.3 I am able to work with HH:MM format, but in CentOS 7 with sysstat 10.1.5 I reproduced the problem you reported. Seems the old version is more restrictive and needs HH:MM:SS format. Fixed with your pull request (thanks!)

As for the second issue, matplotlib seems to be trying to use the X server. Since sarviewer is intended to work in servers without graphic interface, I added the following at the beginning of all Python matplotlib scripts:
```
import matplotlib
matplotlib.use('Agg')
```
This should work when generating the graphs in a non-interactive backend 
https://matplotlib.org/faq/howto_faq.html#generate-images-without-having-a-window-appear

Regards,
Jota

**Closed as completed** 2018-01-12 06:08 UTC
Labels: bug
